image:
  file: .gitpod.Dockerfile
tasks:
 - name: Setup environment variables for ESP-IDF
   command: |
     source /home/gitpod/.espressif/frameworks/esp-idf-v4.4/export.sh > /dev/null 2>&1
vscode:
  extensions:
    - espressif.esp-idf-extension
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one
ports:
  - port: 9012
    visibility: public
  - port: 9333
    visibility: public